### ISSUE TITLE
generateLocalKey and validateLocalKey

### ISSUE THREAD

**Issue by dageci** [markustenghamn/WHMCS-Licensing-Addon-C-Tester#1]
First I want to thank you for this great work.
Could you maybe add a simple sample for the generateLocalKey and validateLocalKey?
Davor

**Comment by uberswe** [comment]
Hey @dageci, I'm glad you found this project useful. Unfortunately I have not renewed my WHMCS license for many years and it has been 5 years since I wrote this code. Therefore I am not sure how relevant the code is but I will do my best to answer your question.

You are referring to two placeholder functions here https://github.com/uberswe/WHMCS-Licensing-Addon-C-Tester/blob/d27ec36b3db75012bb53e998170a65dc3259f050/src/WHMCS%20License%20Test%20CSharp/Form1.cs#L212

I will write pseudo code, I hope that's ok. So an example for how you might generate a local key and then validating it might be like this:

```
        private string generateLocalKey()
        {
            return AES256Encrypt(secretKey, userIdentifier + timestamp)
        }

        private bool validateLocalKey(localKey)
        {
            content = AES256Decrypt(secretKey, localKey)
            timestamp = content.Replace(userIdentifier, "")
            if IsLessThan30DaysOld(timestamp) {
                return true
            }
            return false
        }
 ``` 
 
 So here we encrypt some values and a timestamp and the encrypted string becomes our key. We can then decrypt our key at anytime and check the timestamp for validity. Implementations can vary a lot. You may want to fetch the secret from a remote server and have every instance have a unique secret. You might also want to profile the system which the application is running on and store a hash or something similar in the key to prevent users from sharing local keys and such. It all depends on what the requirements of the software are and how much user privacy matters and so on.

**Comment by dageci** [comment]
Thank you very much @uberswe this was very helpful.
